name: Update Skate Schedule

on:
  schedule:
    - cron: '0 * * * *'  # runs every hour
  workflow_dispatch:      # allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true 

      - name: Run Open Hockey scraper
        run: uv run open_hockey.py

      - name: Run Public Skate scraper
        run: uv run public_skates.py
